__Python: NumPy__

__1. NumPy: type, dtype, shape, dimension, size__

In [2]:
import numpy as np
# 1차원 array
a = np.array([7,8,9,10,11])
print(f'{a}\n{"object type:":>12} {type(a)}\n{"data type:":>12} {a.dtype}\n{"shape:":>12}\ {a.shape}\n{"dimension:":>12} {a.ndim}\n{"array size:":>12} {a.size}')
a1 = np.array([a]); print(a1.shape)

[ 7  8  9 10 11]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape:\ (5,)
  dimension: 1
 array size: 5
(1, 5)


In [8]:
# 2차원 array
b = np.array([[1.0,2,3,4,5],[8,9,10,11,12.2]])
print(f'{b}\n{"object type:":>12} {type(b)}\n{"data type:":>12} {b.dtype}\n{"shape:":>12}\ {b.shape}\n{"dimension:":>12} {b.ndim}\n{"array size:":>12} {b.size}')

[[ 1.   2.   3.   4.   5. ]
 [ 8.   9.  10.  11.  12.2]]
object type: <class 'numpy.ndarray'>
  data type: float64
      shape:\ (2, 5)
  dimension: 2
 array size: 10


In [9]:
# 3차원 array
c = np.array([[[1,2,3,4,5],[8,9,10,11,12]],[[4,5,6,7,8],[10,11,12,13,14]]])
print(f'{c}\n{"object type:":>12} {type(c)}\n{"data type:":>12} {c.dtype}\n{"shape:":>12}\ {c.shape}\n{"dimension:":>12} {c.ndim}\n{"array size:":>12} {c.size}')

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
object type: <class 'numpy.ndarray'>
  data type: int32
      shape:\ (2, 2, 5)
  dimension: 3
 array size: 20


__2.Numpy: special arrays and indexing__

In [10]:
a_zeros = np.zeros((2,3))
print(a_zeros)
a_ones = np.ones((2,4), dtype=int)
print(a_ones)
a_full = np.full((2,5),7)
print(a_full)
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
a_ran = np.random.random((2,3,4))
print(f'{a_ran}\n{a_ran.dtype}')

[[[0.14913049 0.45849829 0.90680777 0.90538116]
  [0.55266942 0.26561441 0.83179573 0.731039  ]
  [0.49590876 0.82633299 0.379211   0.46205975]]

 [[0.42435449 0.956473   0.98313358 0.17184004]
  [0.0299342  0.57167556 0.08222735 0.98552746]
  [0.60551021 0.58707599 0.88020808 0.34647572]]]
float64


In [13]:
print(c)
print(c[1,0,4])
print(c[0,0,4])

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
8
5


__3. NumPy: flattening and making arrays with arrange function__

In [14]:
print(c)
l = []
for i in c:
    for j in i:
        for k in j:
            l.append(k)
print(f'{l}\n{np.array(l)}')

# flattening
print(np.array(c.flat))

[[[ 1  2  3  4  5]
  [ 8  9 10 11 12]]

 [[ 4  5  6  7  8]
  [10 11 12 13 14]]]
[1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 4, 5, 6, 7, 8, 10, 11, 12, 13, 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]
[ 1  2  3  4  5  8  9 10 11 12  4  5  6  7  8 10 11 12 13 14]


In [15]:
g = np.arange(21)
print(f'{g}\n{type(g)}')
print(g.reshape(1,3,7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]]


In [16]:
h = np.arange(5,21,2)
print(h)
print(np.arange(1, 21).reshape(2, 10))

[ 5  7  9 11 13 15 17 19]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [18]:
a_ss = np.linspace(0,1,11)
print(f'{a_ss}\n{a_ss.shape}\n{a_ss.size}')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
11


__4. NumPy: Array operations__

In [3]:
xa = np.array([[1,2],[3,4],[5,6]])
xb = np.array([[3,4],[5,6],[7,8]])
print(xa.shape, xb.shape)
print(f'{xa+xb}\n{xa*2}')

(3, 2) (3, 2)
[[ 4  6]
 [ 8 10]
 [12 14]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [5]:
print(np.add(xa,xb))
print(np.subtract(xa,xb))
print(np.multiply(xa,xb))
print(np.sqrt(xa))

[[ 4  6]
 [ 8 10]
 [12 14]]
[[-2 -2]
 [-2 -2]
 [-2 -2]]
[[ 3  8]
 [15 24]
 [35 48]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [6]:
xc = np.ones((2,1))
print(xc, xc.shape, xc.ndim)
print(xa.dot(xc))
print(np.dot(xb,xc))

[[1.]
 [1.]] (2, 1) 2
[[ 3.]
 [ 7.]
 [11.]]
[[ 7.]
 [11.]
 [15.]]


In [7]:
xd = np.array([[1,2],[1,2]]); print(xd)
print(np.dot(xa,xd)); print(np.dot(xb,xd))

[[1 2]
 [1 2]]
[[ 3  6]
 [ 7 14]
 [11 22]]
[[ 7 14]
 [11 22]
 [15 30]]


In [9]:
print(xa.T)
print(xb+3)
print(xb)
xb+=3
print(xb)

[[1 3 5]
 [2 4 6]]
[[ 9 10]
 [11 12]
 [13 14]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 9 10]
 [11 12]
 [13 14]]


__5. NumPy: Broadcasting__

In [12]:
ya = np.arange(1,10).reshape(3,3); print(ya)
yv1 = np.ones((3,1)); print(yv1)
yb = ya + yv1; print(yb)
yv2 = np.full((1,3),2); print(yv2)
yc = ya + yv2; print(yc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.]
 [1.]
 [1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


__6. NumPy: Summary Statistics__

In [13]:
print(yc.sum(), yc.mean(), yc.min(), yc.max(), yc.var(), yc.std())
print(yc.argmax(), yc.argmin())
print(yc.mean(axis=0), yc.mean(axis=1))

63 7.0 3 11 6.666666666666667 2.581988897471611
8 0
[6. 7. 8.] [ 4.  7. 10.]


__7. NumPy: Slicing, Flatten, and Stacking__

In [14]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[0], karray[0,:4])
print(karray[:2])
print(karray[:2,:3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[0 1 2 3 4 5 6] [0 1 2 3]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0 1 2]
 [7 8 9]]


In [21]:
karray = np.arange(21).reshape(3,7); print(karray)
print(karray[[0,2]])
print(karray[:,[1,5]])
print(karray[:,1:5])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]]
[[ 1  5]
 [ 8 12]
 [15 19]]
[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [19]:
karray = np.arange(21).reshape(3,7); print(karray)
fkarray = karray.flatten()
print(fkarray, fkarray.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (21,)


In [23]:
Array1 = np.array([[1,2],[3,4],[5,6]])
Array1.T + 1

array([[2, 4, 6],
       [3, 5, 7]])